<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Requests' => array($vendorDir . '/rmccue/requests/library'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'Parsedown' => array($vendorDir . '/blesta/parsedown'),
    'Base2n' => array($vendorDir . '/blesta/binary-to-text-php'),
);
